# Generated by Django 3.1.5 on 2021-01-21 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_empleados',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'view_empleados',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='celular',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='correo_electronico',
            field=models.EmailField(default='correo@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='genero',
            field=models.CharField(default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
    ]
